server:
  port: 8080
#  servelet:
#    context-path: /contratados

# data source
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:contratados
    username: sa
    password:

  # jpa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  # h2
  h2:
    console:
      enabled: true
      path: /h2-console

# jwt
contratados:
  jwt:
    secret: A+X;fTJP&Pd,TD9dwVq(hsHX,ya^<wsD_UK7L+@=S;{'CydP]{v@}G'b>et;yz$*\yL5S8EJN:%P:X%H9>#nYLrX}@\s?CQcpspH,2emzBc!Q[V'AYa~uzF8WR~AUrMzxp/V$9([S9X#zj/CH('#]B_Hc+%fGhe27YB;^j4\Xk=Ju"Ap~_&<L;=!Z;!,2UP;!hF3P]j85#*`&T]/kB/W^6$v~u6qpejL>kY^f)sy4:qTq_Ec!-z!@aAp~sLKGU>$
    expiration: 86400000
    security:
      basic:
        enabled: false